### ISSUE TITLE
app.configure() should handle ESM default exports

### ISSUE THREAD

**Issue by toddgeist** [feathersjs/docs#1126]
### app.configure() will throw an error if handed an ES Module with a default export
this will not work in middleware/index.js
```
export default function(app) {
  app.use("/path", (req, res, next) => {
    console.log("basicAuth middleware is running");
    next();
  });
}
```
=> `TypeError: fn.call is not a function`

with the release of https://github.com/standard-things/esm it is trivial to use ESM in node. This mostly works with feathers, but this is one area where it doesn't.

There is a trivial fix here
https://github.com/feathersjs/feathers/blob/0fa518b6cdabf285b543b9cb192c8bf207d589e3/lib/application.js#L58
```
  configure(fn) {
    if (fn.default) {
      fn = fn.default;
    }
    fn.call(this, this);

    return this;
  },
```

I can do a PR, if this makes sense.  Or is ESM support planned for the future?

### System configuration (optional)
I added this to the top of a generated app
require = require("esm")(module /*, options*/);

**NodeJS version**: 8.9

**Operating System**: Mac OSX

**Browser Version**: na

**React Native Version**:na

**Module Loader**:ESM - https://github.com/standard-things/esm

**Comment by daffl** [comment]
Personally I would prefer to not handling module loader idiosyncrasies. Shouldn't `import something from './myconfigure'` already just contain the default export (of course `import * as something from './myconfigure'` won't)?

**Comment by toddgeist** [comment]
I suppose the problem is really just that the generator produces common js syntax. so when  the middleware gets applied it is happening via require(), and require doesn't handle esm "default". Import would though.

So maybe if you are going to mix common.js and esm then sometimes you are going to need to need use export.modules

**Comment by daffl** [comment]
True, the generator will definitely ultimately use ES modules but there is unfortunately a lot of work involved updating the code transformations for it. The primary goal of the generator is to create code that works in the latest version of Node without any additional transpiler steps (no TypeScript, Babel etc.).

ESM definitely makes ES module support more realistic since it can just be loaded like a normal dependency but I think the solution really is for the whole app to be generated using ES modules.

**Comment by toddgeist** [comment]
I agree.  Is that a doable thing? 

Maybe'll take a look at the generator.  Can you suggest an approach?

**Comment by daffl** [comment]
The approach would be to update the generator files to ES modules first. The Codemod tools are in https://github.com/feathersjs/tools and each generator has its own code transformation section (e.g. https://github.com/feathersjs/generator-feathers/blob/master/generators/service/index.js#L99).

**Comment by daffl** [comment]
I'm going to close this issue since I think we agree the best way to solve it will be to start supporting ES modules (we can track progress in a new issue). Thank you for your input @toddgeist!

**Comment by dkebler** [comment]
What issue is that?   

Since last April has there any movement toward an es6/esm version of feathersjs?  

Not that I can't continue to code this part of my larger application in es5/cjs but with node 11+ and dalton's esm  i've gone "native" (without babel I mean) es6/esm for the entire rest of my project
