### ISSUE TITLE
How to join channel based on initial URL 

### ISSUE THREAD

**Issue by aksperiod** [feathersjs/docs#1141]
Hi there,

First off, I just started using feathers.js and it's awesome! However, I've hit a roadblock.

A common use-case I've seen with socket.io apps is to implement rooms based on the pathname, such that if I go to room `localhost:3030/general` it would subscribe me to the `general` channel, and so on and so forth, however I have been reading the docs and I don't see a way to join a channel from the client without going through an authentication step. I don't even see any way to pass initial `io()` configuration to the server besides `timeout`, seen [here](https://docs.feathersjs.com/api/client/socketio.html#socketiosocket-options). Maybe I'm reading in the wrong place?

Any insights would be greatly appreciated.

**Comment by daffl** [comment]
The `io` configuration on the client happens when you establish the socket connection (`const socket = io('http://api.feathersjs.com');`) which is just a normal [Socket.io client](https://socket.io/docs/client-api/) with all its options.

Since Websockets don't really know about URLs you will have to pass that information manually. The secret to getting it into Feathers is using [socket.feathers in a Socket.io middleware](https://docs.feathersjs.com/api/socketio.html#appconfiguresocketiocallback):

```js
app.configure(socketio(function(io) {
  // Registering Socket.io middleware
  io.use(function (socket, next) {
    const room = parseRoomFromRequest(socket.request);

    socket.feathers.room = room;
    next();
  });
}));
```

The [`connection` for channels](https://docs.feathersjs.com/api/channels.html) is the exact same object as `socket.feathers` so you can now just read it and join on connection:

```js
app.on('connection', connection => {
  const { room } = connection; // socket.feathers.room
  if(room) {
    app.channel(room).join(connection);
  }
});
```
