### ISSUE TITLE
Authenticated, but the service is still unauthorized

### ISSUE THREAD

**Issue by Tunizoo** [feathersjs/docs#1382]
I have created the users service, and another service called devices..
The second service is still unauthorized, although I use the authentication procedure?

**Comment by daffl** [comment]
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by Tunizoo** [comment]
Thanks. I have found half of the solution: it is to add the token key to
the ajax request to get the data through the 'devices' service . But I
recommend you to specify the solution in this situation: the situation of
accessing a service other than 'users', when it needs authentication.

‫في الجمعة، 11 أكتوبر 2019 في 4:18 م تمت كتابة ما يلي بواسطة ‪David
Luecke‬‏ <‪notifications@github.com‬‏>:‬
