### ISSUE TITLE
Comment: File uploads in FeathersJS (cookbook/express/file-uploading.md)

### ISSUE THREAD

**Issue by x1smind** [feathersjs/docs#1389]
### Comment/Problem

This page is referring to ".model" and ".filter" files which are no longer used in v4.

In [Basic upload with feathers-blob and feathers-client], the variable createService is defined but never used in the example code provided ->>>const createService = require('feathers-nedb');<<<

This also appears to be using code from previous feathers versions.

**Comment by daffl** [comment]
It would be great if somebody was interested in updating the guide accordingly.

**Comment by asamolion** [comment]
@daffl I've recently written an uploader service in feathers that uses streams to upload. However the catch is that it bypasses feathers altogether and just becomes a regular express controller.

I had to do this to because I needed access to the req object. Is that something that should go in the docs?
