### ISSUE TITLE
auth0Id and profile information is missing most of the times

### ISSUE THREAD

**Issue by kashifnazar** [feathersjs/docs#1454]
### Comment/Problem

When a user logins in to the application, most of the times `auth0Id` appears to be null. Actually, if we console log `baseData` and `profile` in the extended `Auth0Strategy` class shown in the [cookbook](https://docs.feathersjs.com/cookbook/authentication/auth0.html), both of these values are empty objects.

This happens like 90% of times, mostly when a user had already logged in and Auth0 was able to identify the user without promoting for username and password.

How can we make sure that we always get the `auth0Id` when Auth0 redirects back to the Feathers server? 

**Operating System**:
Windows 10

**Comment by kashifnazar** [comment]
[cookbook](https://docs.feathersjs.com/cookbook/authentication/auth0.html)

**Comment by daffl** [comment]
For some providers, the 

```
"scope": ["openid", "profile", "email"],
```

Option needs to be included. I added it to [the docs](https://docs.feathersjs.com/cookbook/authentication/auth0.html).

Additionally, if you are using a custom social connection client id (instead of the the default Auth0 dev keys), the [getProfile](https://docs.feathersjs.com/api/authentication/oauth.html#getprofile-data-params) method has to be customized to get the profile from the provider instead of auth0.

**Comment by kashifnazar** [comment]
> For some providers, the
> 
> ```
> "scope": ["openid", "profile", "email"],
> ```
> 
> Option needs to be included. I added it to [the docs](https://docs.feathersjs.com/cookbook/authentication/auth0.html).
> 
> Additionally, if you are using a custom social connection client id (instead of the the default Auth0 dev keys), the [getProfile](https://docs.feathersjs.com/api/authentication/oauth.html#getprofile-data-params) method has to be customized to get the profile from the provider instead of auth0.

Thanks. That works like a charm.
