### ISSUE TITLE
Create a guide for many to many relationships

### ISSUE THREAD

**Issue by ekryski** [feathersjs/docs#51]
This keeps coming up over and over again and we need to have a concrete example we can point to for how you deal with many to many relationships with Feathers. We do have some stuff [in the FAQ](http://docs.feathersjs.com/help/faq.html#the-orm-way) but I think we need a real guide.

Some related discussions to go off of:
- https://github.com/feathersjs/feathers-sequelize/issues/12
- https://github.com/feathersjs/feathers-sequelize/issues/16

**Comment by niallobrien** [comment]
What's the preferred method?

**Comment by ekryski** [comment]
@niallobrien I'm pushing something up today

**Comment by niallobrien** [comment]
Awesome, thanks.

**Comment by sscaff1** [comment]
Any updates on this?

**Comment by ekryski** [comment]
@sscaff1 yes sorry I have some stuff in the works, basically if you need simple population you can just use the feathers `populate` hook and if you need more complex stuff you currently need to drop into sequelize by passing `hook.params.sequelize` options. If you search the github issues for the feathers org a bunch of stuff should come up.

I've been bogged down with work and we're not using sequelize so I'm hoping to have this guide wrapped up next week.

**Comment by lobosan** [comment]
Hi @ekryski, hope you are doing well. I was wondering if the guide is ready? if so where can I find it? and if not, then can you say when this would be available? Thanks for your help.

**Comment by ekryski** [comment]
I'm not sure if this is required any more since the new generator/cli v2.0.0, sets up the sequelize model structure for you automatically and you simply defined your many-to-many relationships [the way sequelize tells you to](http://docs.sequelizejs.com/en/latest/docs/associations/#nm).

The one thing might be related to population. @DesignByOnyx you wouldn't be up for writing a blog post would you? That way we can stop answering questions in Slack and just point people to the post.

**Comment by DesignByOnyx** [comment]
I certainly don't mind writing a blog post regarding population. You are correct that the new generators make it easy to define relationships. However, the "populate" hook is still broken with sequelize and there is some work which being done to fix that (read [here](https://github.com/feathersjs/feathers-hooks-common/issues/144#issuecomment-291428967). I am also working on a sequelize "include" hook which can be used by sequelize users to take advantage of SQL joins.

**Comment by eddyystop** [comment]
@DesignByOnyx have you spoken to @daffl about having `instantiate` and `serialize` hooks in `feathers-sequelize`? That way we can get https://github.com/feathersjs/feathers-hooks-common/issues/144#issuecomment-291428967 moving along.

**Comment by daffl** [comment]
This is now out of scope for the documentation. The database adapters document how to integrate with the ORM of choice. Blog posts are always welcome of course.

**Comment by delebash** [comment]
According to the docs the preferred way is without using the orm adapters.  As outlined [here](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-associations).  The only example is the chat application but further examples and explanation of the proper way to use hooks to create relationships would be helpful such as a simple userrole or three table one to many and many to many example using the cli as the starting point would be appreciated.  Thanks.

**Comment by daffl** [comment]
The [FAQ on associations](https://docs.feathersjs.com/faq/readme.html#how-do-i-do-associations) has links to examples and plugins that can help with this.

**Comment by edwardsmarkf** [comment]
my two cents worth - every many-many relationship will end up resolving
into:  one---->>many<<-----one

Thank you,

Mark Edwards

**Comment by delebash** [comment]
David that is what I was talking about in the FAQ the only example of not using an ORM is the chat application or as an alternative way of using a plugin.  You have examples of using an ORM but more examples of using the preferred method besides just the chat app such as user-role or a three table one to many would be very helpful.  Thanks.

How do I do associations?

Similar to validation, it depends on if your database/ORM supports models or not.

The preferred way

For any of the feathers database/ORM adapters you can just use hooks<https://docs.feathersjs.com/api/hooks.html> to fetch data from other services.

This is a better approach because it keeps your application database agnostic and service oriented. By referencing the services (using app.service().find(), etc.) you can still decouple your app and have these services live on entirely separate machines or use entirely different databases without having to change any of your fetching code. We show how to associate data in a hook in the chat guide<https://docs.feathersjs.com/guides/chat/processing.html>. An alternative are the fastJoin<https://feathers-plus.github.io/v1/feathers-hooks-common/#fastjoin> or populate<https://feathers-plus.github.io/v1/feathers-hooks-common/#populate> in feathers-hooks-common<https://feathers-plus.github.io/v1/feathers-hooks-common/>.

The ORM way


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
