### ISSUE TITLE
Comment: REST APIs (guides/basics/rest.md)

### ISSUE THREAD

**Issue by aral** [feathersjs/docs#973]
After you delete the first message, if you issue a GET on /messages/1, you get a 500 error as the `get` method from our `Messages` class throws when it can’t find a message.

Would it be a good idea to make this return a 404 instead at this point in the tutorial or would that be rushing ahead?

**Comment by daffl** [comment]
I think that's a good call to introduce in the services chapter since we're using it in the following (Hooks) chapter already anyway.

**Comment by daffl** [comment]
Ah, the issue is that in that case the code for client and server will diverge because on the server we'll need to import `@feathersjs/errors` and on the client it will be `feathers.errors`.

The difference is explained in the [client API chapter](https://docs.feathersjs.com/api/client.html) but for some reason it still seems to cause confusion so I'd rather introduce it at a later point.
